recommend_movie/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('signin/', views.signin, name='signin'),
  path('logout/', views.logout, name='logout'),
]

recommend_movie/home/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
  path('', views.index, name="index"),
  path('movie_list/', views.movie_list, name="movie_list"),
]

recommend_movie/recommend_movie/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]

recommend_movie/accounts/models.py
from django.db import models

# Create your models here.

recommend_movie/home/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
  genre = models.CharField(max_length=10)

class Director(models.Model):
  director = models.CharField(max_length=20)

class Actor(models.Model):
  actor = models.CharField(max_length=20)

class Movie(models.Model):
  # 영화 정보
  # 제목, 내용, 개봉일, 포스터
  # foreignkey 묶을것
  # 감독, 배우, 장르, 댓글, 좋아요, 싫어요
  # 점수는 따로 뺄 것. => 계산 쉽게
  title = models.CharField(max_length=50)
  content = models.TextField()
  poster = models.TextField()
  opened_at = models.DateTimeField()

  genres = models.ManyToManyField(Genre, related_name="movies")
  directors = models.ManyToManyField(Director, related_name="filmo")
  actors = models.ManyToManyField(Actor, related_name="filmo")

# class Score(models.Model):
#   score = models.IntegerField()
#   movie = models.ForeignKey(Movie, on_delete=models.CASCADE) # 삭제 시 같이 삭제
  

recommend_movie/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
  class Meta:
    model = get_user_model()
    fields = ['username', 'first_name', 'email', 'password1', 'password2']

recommend_movie/accounts/views.py
from django.shortcuts import render, redirect
# 로그인 form, 로그인 유지
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import UserCustomCreationForm

# Create your views here.
def signup(request):
  # 만약 이미 로그인 되어있으면 메인으로 redirect
  if request.user.is_authenticated:
    return redirect('movies:index')
  # 만약 form 으로 요청이 올 경우
  if request.method == "POST":
    user_form = UserCustomCreationForm(request.POST)
    # 만약 들어온 값이 유효하면 저장
    if user_form.is_valid():
      user_form.save()
      return redirect('movies:index')
  else:
    user_form = UserCustomCreationForm()
  context = {'user_form': user_form}
  return render(request, 'accounts/signup.html', context)

def signin(request):
  # 만약 이미 로그인 되어있으면 메인으로 redirect
  if request.user.is_authenticated:
    return redirect('movies:index')
  # POST요청으로 들어올 경우 유효하면 로그인
  if request.method == 'POST':
    signin_form = AuthenticationForm(request, request.POST)
    if signin_form.is_valid():
      auth_login(request, signin_form.get_user())
      return redirect('movies:index')
  else:
    signin_form = AuthenticationForm()
  context = {'signin_form': signin_form}
  return render(request, 'accounts/signin.html', context)

def logout(request):
  auth_logout(request)
  return redirect('movies:index')

recommend_movie/home/views.py
import random

from django.shortcuts import render, HttpResponse

# Create your views here.
def index(request):
  print(request)
  movie_list = ['겨울왕국2', '블랙머니', '조커']

  movie = random.choice(movie_list)
  return render(request, 'home/index.html', {'movie': movie})
  # return HttpResponse("hello, django!")


def movie_list(request):
  movie_list = ['겨울왕국2', '블랙머니', '조커']

  return render(request, 'home/movie_list.html', {'movie_list': movie_list})

recommend_movie/accounts/templates/accounts/signin.html
{% extends "base.html" %}
{% block css %}
<style>

input{
  display: block;
  margin: 10px auto;
  margin-bottom: 16px;
  border: solid 1px skyblue;
  background-color: white;
  height: 26px;
  width: 60vw;
  max-width: 300px;
}
.submit{
  margin-top:40px;
  font-size: 16px;
  width: 30vw;
  max-width: 140px;
}
.signup_link{
  margin-top: 100px;
  text-align: center;
}
.signup_link>p{
  margin: 5px 0px;
}
#signup_link{
  border: 1px solid skyblue;
  background-color: white;
  padding: 3px 15px;
  font-size: 16px;
  margin-top: 10px;
}
</style>
{% endblock %}

{% block body %}
<h1>Sign In</h1>
<form class="account" method="POST">
  {% csrf_token %}
  {% for field in signin_form %}
  {% if field.html_name == "username" %}
    <label for="id_{{ field.html_name }}">ID</label>
  {% else %}
    <label for="id_{{ field.html_name }}">비밀번호</label>
  {% endif %}
    {{field}}
  {% endfor %}
  <input class="submit" type="submit" value="로그인">
</form>
<div class="signup_link">
  <p>아직 '오늘의 영화' 회원이 아니시라구요?</p>
  <p>아래 버튼을 눌러 많은 서비스를 즐겨보세요!</p>
  <a href="/accounts/signup/"><button id="signup_link">회원가입</button></a>
</div>
{% endblock %}

recommend_movie/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block css %}
<style>

input{
  display: block;
  margin: 10px auto;
  margin-bottom: 16px;
  border: solid 1px skyblue;
  background-color: white;
  height: 26px;
  width: 60vw;
  max-width: 300px;
}
.submit{
  margin-top:40px;
  font-size: 16px;
  width: 30vw;
  max-width: 140px;
}
</style>
{% endblock %}
{% block body %}
<h1>Sign Up</h1>
<form method="POST" id="signup" class="account">
  {% csrf_token %}
  {% for field in user_form %}
    <div class="form-group">
      {% if field.html_name == 'username' %}
      <label for="id_{{field.html_name}}">ID</label>
      {% else %}
      <label for="id_{{field.html_name}}">{{ field.label }}</label>
      {% endif %}
    </div>
    {{ field }}
  {% endfor %}
  <input class="submit" type="submit" value="가입">
</form>
{% endblock %}

recommend_movie/home/templates/home/index.html
{% extends 'base.html' %}
{% block css %}
<style>

.movie_card{
  width: 50%;
  height: 300px;
  border: 1px solid black;
  margin: 10px auto;
}
</style>
{% endblock %}
{% block body %}
<h1>Today Movie</h1>
<div id="main_movie" class="movie_card">
  이 안에 포스터가 들어갈거에요~
</div>
<h2>{{movie}}</h2>

{% endblock %}

recommend_movie/home/templates/home/movie_list.html
{% extends 'base.html' %}

{% block body %}
<h1>movie list</h1>
{% for movie in movie_list %}
  <li>{{movie}}</li>
{% endfor %}


{% endblock %}

recommend_movie/recommend_movie/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>rain's Movie</title>
  {% block css %}{% endblock %}
</head>
<body>
  <a class="menu-trigger" href="#">
    <span></span>
    <span></span>
    <span></span>
  </a>
  <div class="menu-list">
    <li><a href="/">Home</a></li><hr>
    {% if user.is_authenticated %}
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li><hr>
    {% else %}
      <li><a href="{% url 'accounts:signin' %}">Sign In</a></li><hr>
    {% endif %}
    <li><a href="/movie_list/">Movie List</a></li>
  </div>
  {% block body %}
  {% endblock %}
</body>
{% block script %}
{% endblock %}
</html>

<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

<script>
  // 햄버거 버튼을 누를 때 메뉴 리스트 출력
  let burger = $('.menu-trigger');
  let menu_list = $('.menu-list');

  var $this = $(this);
  burger.each(function(index){
    var $this = $(this);
    // burger를 클릭하는 이벤트 발생 시
    $this.on('click', function(e){
      e.preventDefault();
      // burger와 menu_list를 active
      $(this).toggleClass('active');
      menu_list.toggleClass('active');
    })
  });

  $(function(){
    let elements = $('label:eq(0)');
    console.log(elements);
  })
</script>

<style>
@import url('https://fonts.googleapis.com/css?family=Black+Han+Sans|Nanum+Gothic:400,700,800&display=swap&subset=korean');
  *{
    margin: 0;
    padding: 0;
    font-family: 'Nanum Gothic', sans-serif;
    background-color: #f2f2f2;
  }
  a{
    text-decoration: none;
  }

  .menu-trigger {
    margin: 15px;
  }
  .menu-trigger,
  .menu-trigger span {
    display: inline-block;
    transition: all .4s;
    box-sizing: border-box;
  }

  .menu-trigger {
    position: relative;
    width: 36px;
    height: 30px;
  }

  .menu-trigger span {
    position: absolute;
    left: 0;
    width: 100%;
    height: 4px;
    background-color: rgb(190, 218, 255);
    border-radius: 4px;
  }

  .menu-trigger span:nth-of-type(1) {
    top: 0;
  }

  .menu-trigger span:nth-of-type(2) {
    top: 13px;
  }

  .menu-trigger span:nth-of-type(3) {
    bottom: 0;
  }

  .menu-trigger.active span:nth-of-type(1),
  .menu-trigger.active span:nth-of-type(3) {
    width : 13px;
  }
  .menu-trigger.active span:nth-of-type(1) {
    -webkit-transform : translate(0px, 8px) rotate(-45deg);
    transform : translate(0px, 8px) rotate(-45deg);
  }
  .menu-trigger.active span:nth-of-type(3) {
    -webkit-transform : translate(0px, -8px) rotate(45deg);
    transform : translate(0px, -8px) rotate(45deg);
  }

  .menu-list {
    display: none;
  }

  .menu-list.active {
    display: block;
    padding: 0px 10px;
    font-size: 30px;
    text-align: center;
    margin-bottom:30px;
    height: 100vh;
  }

  .menu-list.active>li{
    list-style: none;
    margin: 5px 0px;
  }

  .menu-list.active>li>a:link{
    color: black;
  }
  .menu-list.active>li>a:visited{
    color: black;
  }
  .menu-list.active>li>a:hover{
    color: rgb(190, 218, 255);
  }

  h1{
    font-size: 40px;
    font-family: 'Black Han Sans', sans-serif;
    margin: 5px;
    text-align: center;
    color: #8ab7fe;
  }
  h2{
    font-size: 30px;
    margin: 5px;
    text-align: center;
  }

  form.account{
    margin: 10px auto;
    margin-top: 40px;
    text-align: center;
    font-size: 16px;
  }
  form>ul {
    display: none;
  }
  span.helptext {
    display: none;
  }
</style>